services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    restart: unless-stopped
    env_file: .env
    networks:
      - main
    volumes:
      - data:/var/lib/postgresql/data

networks:
  main:
    name: main
    external: true

volumes:
  data:
