services:
  auth-web:
    container_name: auth-web
    image: ghcr.io/emitra-labs/auth-web:main
    restart: unless-stopped
    env_file: .env
    networks:
      - main

networks:
  main:
    name: main
    external: true
