services:
  api-gateway:
    container_name: api-gateway
    image: ghcr.io/emitra-labs/api-gateway:main
    restart: unless-stopped
    env_file: .env
    networks:
      - main
    ports:
      - 127.0.0.1:13000:3000

networks:
  main:
    name: main
    external: true
