services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:3.13-management-alpine
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:5672:5672
    networks:
      - main
    volumes:
      - data:/var/lib/rabbitmq

networks:
  main:
    name: main
    external: true

volumes:
  data:
